### ISSUE TITLE
Exporter "lastbackup" timestamp unit for visualization

### ISSUE THREAD

**Issue by Kybeer** [raph2i/synology_backup_exporter#6]
Hi @raph2i ,

Thanks for the excellent exporter. I'm visualizing the metrics in Grafana, and wonder if you know what unit (in the Grafana Dashboard options - Standard options - Unit) to use for those two metrics? 

synology_hyper_backup_lastbackup_successful_timestamp
synology_hyper_backup_lastbackup_timestamp

Datetime doesn't seem to be correct ones. It shows 1970-01-20 on all metrics.

**Comment by raph2i** [comment]
Hi @Kybeer 

timestamp is an usual unix timestamp

This query gives me the hours since last backup:

```
((synology_active_backup_lastbackup_timestamp - time()) / 3600)
```

![grafik](https://user-images.githubusercontent.com/55005474/192118898-0e12f34f-d402-4e68-af29-edae1c57f520.png)
